version: '3.7'

services:
  app:    
    build: 
      context:  ./app
    restart: unless-stopped
    expose:
      - "5000"
    ports:
      - "5000:5000"
    nginx:
      container_name: nginx
      build:
        context: ./nginx
      restart: unless-stopped
      expose:
        - "80"
      ports:
        - "8090:80"
      depends_on:
        - app
        


