version: '3.7'

services:
  app:
    restart: always
    build: ./app
    expose:
      -"5000"
    ports:
      -"5000:5000"
    nginx:
      container_name: nginx
      build: ./nginx
      expose:
        -"80"
      ports:
        -"80:80"
      depends_on:
        -app
        


